insert into team (team_id, foundation_date, name, website_url) values (1, '9/4/2006', 'Macejkovic-Reilly', null);
insert into team (team_id, foundation_date, name, website_url) values (2, '10/23/2001', 'Marquardt-Jaskolski', null);
insert into team (team_id, foundation_date, name, website_url) values (3, '5/15/2009', 'Pfannerstill LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (4, '9/7/2010', 'Towne, Vandervort and Hammes', 'towne.com');
insert into team (team_id, foundation_date, name, website_url) values (5, '10/13/2010', 'Macejkovic and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (6, '9/19/2002', 'Paucek, Hammes and Walker', null);
insert into team (team_id, foundation_date, name, website_url) values (7, '3/5/2002', 'Zieme LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (8, '3/5/2002', 'Hilll-Legros', null);
insert into team (team_id, foundation_date, name, website_url) values (9, '5/1/2005', 'Ritchie, Considine and Marvin', 'ritchie-racing.com');
insert into team (team_id, foundation_date, name, website_url) values (10, '4/18/2007', 'Koelpin, Luettgen and Collins', 'koelpin.com');
insert into team (team_id, foundation_date, name, website_url) values (11, '1/11/2001', 'Dickens Group', null);
insert into team (team_id, foundation_date, name, website_url) values (12, '5/19/2008', 'Emmerich-Schuppe', null);
insert into team (team_id, foundation_date, name, website_url) values (13, '5/9/2008', 'Heaney Group', null);
insert into team (team_id, foundation_date, name, website_url) values (14, '12/14/2007', 'Hills, Hackett and Turner', null);
insert into team (team_id, foundation_date, name, website_url) values (15, '9/26/2002', 'Bradtke, McKenzie and Wilkinson', null);
insert into team (team_id, foundation_date, name, website_url) values (16, '1/30/2005', 'Emard Group', null);
insert into team (team_id, foundation_date, name, website_url) values (17, '7/20/2009', 'Bernier-Jast', 'bernier-jast.com');
insert into team (team_id, foundation_date, name, website_url) values (18, '1/19/2005', 'Rohan-Metz', null);
insert into team (team_id, foundation_date, name, website_url) values (19, '11/14/2010', 'Jacobson LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (20, '10/1/2010', 'Sipes and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (21, '7/8/2001', 'Dibbert, Marks and Becker', 'dibbert-racing.it');
insert into team (team_id, foundation_date, name, website_url) values (22, '9/20/2009', 'MacGyver, Monahan and Rempel', null);
insert into team (team_id, foundation_date, name, website_url) values (23, '10/28/2001', 'Abbott and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (24, '6/30/2009', 'Renner, Durgan and Hamill', null);
insert into team (team_id, foundation_date, name, website_url) values (25, '8/4/2001', 'Weber Group', null);
insert into team (team_id, foundation_date, name, website_url) values (26, '5/19/2006', 'Marquardt and Sons', 'marquardt.fr');
insert into team (team_id, foundation_date, name, website_url) values (27, '4/17/2008', 'Jones-Grady', null);
insert into team (team_id, foundation_date, name, website_url) values (28, '3/19/2003', 'Denesik, Collins and Feeney', null);
insert into team (team_id, foundation_date, name, website_url) values (29, '10/19/2010', 'Carter, Marquardt and Eichmann', null);
insert into team (team_id, foundation_date, name, website_url) values (30, '5/15/2003', 'Nienow LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (31, '8/9/2006', 'Hodkiewicz Group', null);
insert into team (team_id, foundation_date, name, website_url) values (32, '11/28/2006', 'Wuckert-Schamberger', null);
insert into team (team_id, foundation_date, name, website_url) values (33, '1/29/2009', 'Treutel, Murphy and Smith', null);
insert into team (team_id, foundation_date, name, website_url) values (34, '11/28/2008', 'Feil Inc', null);
insert into team (team_id, foundation_date, name, website_url) values (35, '1/30/2003', 'Kautzer LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (36, '2/16/2010', 'Torphy, Kuvalis and Tremblay', null);
insert into team (team_id, foundation_date, name, website_url) values (37, '3/13/2001', 'Olson, Hamill and Lakin', null);
insert into team (team_id, foundation_date, name, website_url) values (38, '6/21/2004', 'Botsford LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (39, '7/13/2008', 'Gorczany Inc', 'vk.com/cras/non/velit.js');
insert into team (team_id, foundation_date, name, website_url) values (40, '6/29/2009', 'Murazik-Ebert', 'symantec.com/eu/mi.js');
insert into team (team_id, foundation_date, name, website_url) values (41, '11/22/2005', 'Gerlach Group', 'gerlach-racing-group.de');
insert into team (team_id, foundation_date, name, website_url) values (42, '12/19/2003', 'Bosco LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (43, '12/8/2009', 'Heller, Herman and Lockman', null);
insert into team (team_id, foundation_date, name, website_url) values (44, '1/14/2002', 'Rodriguez, Dibbert and Beahan', null);
insert into team (team_id, foundation_date, name, website_url) values (45, '2/20/2001', 'VonRueden Inc', null);
insert into team (team_id, foundation_date, name, website_url) values (46, '3/11/2006', 'Langworth, Wilderman and Mayert', null);
insert into team (team_id, foundation_date, name, website_url) values (47, '2/10/2004', 'Ferry Group', null);
insert into team (team_id, foundation_date, name, website_url) values (48, '1/10/2001', 'Mertz, Larkin and Schmeler', 'mertz.de');
insert into team (team_id, foundation_date, name, website_url) values (49, '10/10/2005', 'Braun, Dickinson and Beier', 'racing.braun.de');
insert into team (team_id, foundation_date, name, website_url) values (50, '5/29/2009', 'Runolfsdottir, Douglas and Kuhlman', 'okayracing.com');
