delete from driver_group;
delete from driver_sponsor;
delete from circuit_sponsor;
delete from sponsor;
delete from driver;
delete from mechanic;
delete from racecar;
delete from team;
delete from circuit;
commit;
