insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (101, 'Ronni', 'Casassa', '30.07.1989', 1, 'AM', 'ebay.co.uk');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (102, 'Berti', 'Ickovic', '02.06.1982', 1, 'CD', 'fc2.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (103, 'Perry', 'Possel', '06.08.1996', 1, 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (104, 'Joete', 'Andrzejczak', '02.08.1985', 1, 'PH', 'goo.gl');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (105, 'Ulrikaumeko', 'Ludovico', '12.05.1986', 1, 'HR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (106, 'Bella', 'Rowcliffe', '18.07.1985', 1, 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (107, 'Tallie', 'Dullingham', '25.08.1994', 1, 'PL', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (108, 'Ellynn', 'Plume', '28.05.1987', 1, 'NG', 'people.com.cn');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (109, 'Gabey', 'Betchley', '07.06.1991', 1, 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (110, 'Jillian', 'Lotte', '26.01.1982', 1, 'CN', 'nationalgeographic.com');
commit;
