insert into Sponsor (sponsor_id, name, website) values (1, 'Rau LLC', 'google.ru');
insert into Sponsor (sponsor_id, name, website) values (2, 'Barrows LLC', 'constantcontact.com');
insert into Sponsor (sponsor_id, name, website) values (3, 'Howe-Cole', 'craigslist.org');
insert into Sponsor (sponsor_id, name, website) values (4, 'MacGyver-Runolfsdottir', '163.com');
insert into Sponsor (sponsor_id, name, website) values (5, 'Keebler-Leuschke', 'springer.com');
insert into Sponsor (sponsor_id, name, website) values (6, 'Ritchie LLC', 'webmd.com');
insert into Sponsor (sponsor_id, name, website) values (7, 'Sporer-Ernser', 'miibeian.gov.cn');
insert into Sponsor (sponsor_id, name, website) values (8, 'Kihn Group', 'nationalgeographic.com');
insert into Sponsor (sponsor_id, name, website) values (9, 'Bergstrom LLC', 'deviantart.com');
insert into Sponsor (sponsor_id, name, website) values (10, 'Aufderhar Group', '360.cn');
insert into Sponsor (sponsor_id, name, website) values (11, 'Emard-Schumm', 'va.gov');
insert into Sponsor (sponsor_id, name, website) values (12, 'Watsica LLC', 'pbs.org');
insert into Sponsor (sponsor_id, name, website) values (13, 'Towne, Kuhic and Howe', 'cnn.com');
insert into Sponsor (sponsor_id, name, website) values (14, 'Huels, Roob and Zulauf', 'springer.com');
insert into Sponsor (sponsor_id, name, website) values (15, 'VonRueden, Sauer and Hegmann', 'who.int');
insert into Sponsor (sponsor_id, name, website) values (16, 'Bergstrom, Ondricka and Christiansen', 'tmall.com');
insert into Sponsor (sponsor_id, name, website) values (17, 'Reinger Inc', 'webeden.co.uk');
insert into Sponsor (sponsor_id, name, website) values (18, 'Hamill, Mills and Larson', 'ihg.com');
insert into Sponsor (sponsor_id, name, website) values (19, 'Nienow Group', 'hatena.ne.jp');
insert into Sponsor (sponsor_id, name, website) values (20, 'Schimmel, Christiansen and Schuppe', 'goo.ne.jp');
insert into Sponsor (sponsor_id, name, website) values (21, 'Hettinger and Sons', 'usa.gov');
insert into Sponsor (sponsor_id, name, website) values (22, 'Bogan LLC', 'gov.uk');
insert into Sponsor (sponsor_id, name, website) values (23, 'Luettgen-Kovacek', 'cnet.com');
insert into Sponsor (sponsor_id, name, website) values (24, 'Schuppe, Spinka and Kerluke', 'deviantart.com');
insert into Sponsor (sponsor_id, name, website) values (25, 'Lakin, Block and Howe', 'yahoo.co.jp');
insert into Sponsor (sponsor_id, name, website) values (26, 'Friesen, Mann and McKenzie', 'toplist.cz');
insert into Sponsor (sponsor_id, name, website) values (27, 'Greenfelder and Sons', 'ft.com');
insert into Sponsor (sponsor_id, name, website) values (28, 'Brown LLC', 'yandex.ru');
insert into Sponsor (sponsor_id, name, website) values (29, 'Abshire-Heller', 'seesaa.net');
insert into Sponsor (sponsor_id, name, website) values (30, 'Waters, Rau and Koepp', 'weibo.com');
insert into Sponsor (sponsor_id, name, website) values (31, 'Rowe-Altenwerth', 'blogspot.com');
insert into Sponsor (sponsor_id, name, website) values (32, 'Kilback and Sons', 'bloomberg.com');
insert into Sponsor (sponsor_id, name, website) values (33, 'Johnston LLC', 'nasa.gov');
insert into Sponsor (sponsor_id, name, website) values (34, 'Rowe-Dibbert', 'jugem.jp');
insert into Sponsor (sponsor_id, name, website) values (35, 'Douglas, Ziemann and Haag', 'slideshare.net');
insert into Sponsor (sponsor_id, name, website) values (36, 'Christiansen, Ward and Schamberger', 'tinyurl.com');
insert into Sponsor (sponsor_id, name, website) values (37, 'Turner LLC', 'apple.com');
insert into Sponsor (sponsor_id, name, website) values (38, 'Bogan-Pagac', 'opensource.org');
insert into Sponsor (sponsor_id, name, website) values (39, 'Howe, Murray and Haag', 'squarespace.com');
insert into Sponsor (sponsor_id, name, website) values (40, 'Greenholt and Sons', 'ted.com');
insert into Sponsor (sponsor_id, name, website) values (41, 'Daugherty, Lindgren and Heaney', 'webs.com');
insert into Sponsor (sponsor_id, name, website) values (42, 'Nitzsche-Gorczany', 'usda.gov');
insert into Sponsor (sponsor_id, name, website) values (43, 'Beer LLC', 'go.com');
insert into Sponsor (sponsor_id, name, website) values (44, 'Schmeler-McDermott', 'examiner.com');
insert into Sponsor (sponsor_id, name, website) values (45, 'Rippin and Sons', 'google.com');
insert into Sponsor (sponsor_id, name, website) values (46, 'Maggio Group', 'topsy.com');
insert into Sponsor (sponsor_id, name, website) values (47, 'Willms and Sons', 'foxnews.com');
insert into Sponsor (sponsor_id, name, website) values (48, 'Kerluke, Moore and Sipes', 'phoca.cz');
insert into Sponsor (sponsor_id, name, website) values (49, 'Eichmann, Lang and Willms', 'istockphoto.com');
insert into Sponsor (sponsor_id, name, website) values (50, 'Carter Inc', 'pen.io');
insert into Sponsor (sponsor_id, name, website) values (51, 'Gerlach, Macejkovic and Goldner', 'trellian.com');
insert into Sponsor (sponsor_id, name, website) values (52, 'Wolf Group', 'bbb.org');
insert into Sponsor (sponsor_id, name, website) values (53, 'Champlin, Raynor and Gislason', 'cyberchimps.com');
insert into Sponsor (sponsor_id, name, website) values (54, 'Hintz-Schulist', 'ifeng.com');
insert into Sponsor (sponsor_id, name, website) values (55, 'Rippin and Sons', 'unicef.org');
insert into Sponsor (sponsor_id, name, website) values (56, 'Ortiz, Kerluke and McCullough', 'ftc.gov');
insert into Sponsor (sponsor_id, name, website) values (57, 'Hilpert Inc', 'globo.com');
insert into Sponsor (sponsor_id, name, website) values (58, 'Altenwerth, Paucek and Marks', 'free.fr');
insert into Sponsor (sponsor_id, name, website) values (59, 'Kutch, Dooley and Bednar', 'delicious.com');
insert into Sponsor (sponsor_id, name, website) values (60, 'Huels-Tillman', 'gov.uk');
insert into Sponsor (sponsor_id, name, website) values (61, 'Konopelski Group', 'miibeian.gov.cn');
insert into Sponsor (sponsor_id, name, website) values (62, 'Hyatt, Casper and Franecki', 'wunderground.com');
insert into Sponsor (sponsor_id, name, website) values (63, 'Kreiger Inc', 'tiny.cc');
insert into Sponsor (sponsor_id, name, website) values (64, 'Huel, Ledner and Volkman', 'weibo.com');
insert into Sponsor (sponsor_id, name, website) values (65, 'Dickens Group', 'chicagotribune.com');
insert into Sponsor (sponsor_id, name, website) values (66, 'Littel LLC', 'exblog.jp');
insert into Sponsor (sponsor_id, name, website) values (67, 'Lemke and Sons', 'gov.uk');
insert into Sponsor (sponsor_id, name, website) values (68, 'Hayes, Casper and Konopelski', 'ted.com');
insert into Sponsor (sponsor_id, name, website) values (69, 'Russel, Runolfsdottir and Funk', '163.com');
insert into Sponsor (sponsor_id, name, website) values (70, 'Cummerata, Bayer and Hansen', 'google.it');
insert into Sponsor (sponsor_id, name, website) values (71, 'Ryan LLC', 'drupal.org');
insert into Sponsor (sponsor_id, name, website) values (72, 'Fritsch, Boyer and Emard', 'cyberchimps.com');
insert into Sponsor (sponsor_id, name, website) values (73, 'Gerlach and Sons', 'about.com');
insert into Sponsor (sponsor_id, name, website) values (74, 'Brekke, Nicolas and Purdy', 'twitpic.com');
insert into Sponsor (sponsor_id, name, website) values (75, 'Feeney Inc', 'dion.ne.jp');
insert into Sponsor (sponsor_id, name, website) values (76, 'Leannon Group', 'desdev.cn');
insert into Sponsor (sponsor_id, name, website) values (77, 'Christiansen-Borer', 'storify.com');
insert into Sponsor (sponsor_id, name, website) values (78, 'Murphy Inc', 'flavors.me');
insert into Sponsor (sponsor_id, name, website) values (79, 'Connelly and Sons', 'goodreads.com');
insert into Sponsor (sponsor_id, name, website) values (80, 'Borer, Hermiston and Will', 'gmpg.org');
insert into Sponsor (sponsor_id, name, website) values (81, 'Schmidt and Sons', 'wikia.com');
insert into Sponsor (sponsor_id, name, website) values (82, 'Cummerata-Legros', 't-online.de');
insert into Sponsor (sponsor_id, name, website) values (83, 'Sipes-Hahn', 'github.com');
insert into Sponsor (sponsor_id, name, website) values (84, 'Weber, McDermott and Hills', 'kickstarter.com');
insert into Sponsor (sponsor_id, name, website) values (85, 'Schmitt, Miller and Hartmann', 'de.vu');
insert into Sponsor (sponsor_id, name, website) values (86, 'Lubowitz-Mueller', 'godaddy.com');
insert into Sponsor (sponsor_id, name, website) values (87, 'Medhurst, Turner and Osinski', 'exblog.jp');
insert into Sponsor (sponsor_id, name, website) values (88, 'Gutkowski Inc', 'deliciousdays.com');
insert into Sponsor (sponsor_id, name, website) values (89, 'Klocko-Durgan', 'sciencedirect.com');
insert into Sponsor (sponsor_id, name, website) values (90, 'Roob and Sons', 'techcrunch.com');
insert into Sponsor (sponsor_id, name, website) values (91, 'Cummerata, Hills and Stoltenberg', 'about.com');
insert into Sponsor (sponsor_id, name, website) values (92, 'Windler-Nolan', 'hostgator.com');
insert into Sponsor (sponsor_id, name, website) values (93, 'Shanahan, Pollich and Parker', 'tiny.cc');
insert into Sponsor (sponsor_id, name, website) values (94, 'Friesen Inc', 'csmonitor.com');
insert into Sponsor (sponsor_id, name, website) values (95, 'Quigley, Kiehn and Reichel', 'bloomberg.com');
insert into Sponsor (sponsor_id, name, website) values (96, 'Gleichner, Will and McGlynn', 'gov.uk');
insert into Sponsor (sponsor_id, name, website) values (97, 'Heller and Sons', 'desdev.cn');
insert into Sponsor (sponsor_id, name, website) values (98, 'Wiza LLC', 'un.org');
insert into Sponsor (sponsor_id, name, website) values (99, 'Rosenbaum Group', 'admin.ch');
insert into Sponsor (sponsor_id, name, website) values (100, 'Konopelski, Turcotte and Kautzer', 'cnn.com');
commit;
