insert into team (team_id, foundation_date, name, website_url) values (1, '25.03.1975', 'Waters-Keeling', 'ycombinator.com');
insert into team (team_id, foundation_date, name, website_url) values (2, '18.04.1987', 'Smitham-Effertz', null);
insert into team (team_id, foundation_date, name, website_url) values (3, '16.04.1988', 'Torphy and Sons', 'printfriendly.com');
insert into team (team_id, foundation_date, name, website_url) values (4, '11.12.1974', 'Treutel, Hagenes and Ziemann', null);
insert into team (team_id, foundation_date, name, website_url) values (5, '15.01.2000', 'Kunze-Hammes', 'icq.com');
insert into team (team_id, foundation_date, name, website_url) values (6, '14.08.1990', 'Paucek, Cartwright and Kling', 'angelfire.com');
insert into team (team_id, foundation_date, name, website_url) values (7, '23.11.2002', 'McGlynn, Haley and Littel', 'blogtalkradio.com');
insert into team (team_id, foundation_date, name, website_url) values (8, '02.03.1996', 'Medhurst and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (9, '22.10.2002', 'Feeney Inc', null);
insert into team (team_id, foundation_date, name, website_url) values (10, '30.09.1977', 'Kuphal-VonRueden', null);
insert into team (team_id, foundation_date, name, website_url) values (11, '30.01.1972', 'Parisian, Heaney and Abernathy', 'nhs.uk');
insert into team (team_id, foundation_date, name, website_url) values (12, '27.05.1993', 'Littel-Gutkowski', null);
insert into team (team_id, foundation_date, name, website_url) values (13, '18.08.2005', 'Rowe LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (14, '21.07.1987', 'Kohler-Simonis', null);
insert into team (team_id, foundation_date, name, website_url) values (15, '30.07.1979', 'Wuckert-Gerhold', null);
insert into team (team_id, foundation_date, name, website_url) values (16, '09.06.1976', 'Fisher LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (17, '28.07.1977', 'Beahan, Fisher and Abshire', 'nydailynews.com');
insert into team (team_id, foundation_date, name, website_url) values (18, '08.01.2003', 'West, Swaniawski and Hoppe', 'seesaa.net');
insert into team (team_id, foundation_date, name, website_url) values (19, '01.07.1981', 'Mante-Spinka', null);
insert into team (team_id, foundation_date, name, website_url) values (20, '11.05.1972', 'Hahn LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (21, '04.02.1977', 'Rogahn Group', null);
insert into team (team_id, foundation_date, name, website_url) values (22, '13.08.1974', 'Little and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (23, '12.06.1977', 'Tillman and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (24, '09.06.2000', 'Heathcote-Hansen', 'businesswire.com');
insert into team (team_id, foundation_date, name, website_url) values (25, '02.09.1975', 'Ryan, Weissnat and Kuhlman', 'arstechnica.com');
insert into team (team_id, foundation_date, name, website_url) values (26, '14.03.1988', 'Weimann and Sons', 'npr.org');
insert into team (team_id, foundation_date, name, website_url) values (27, '18.05.1972', 'Baumbach-Orn', 'sphinn.com');
insert into team (team_id, foundation_date, name, website_url) values (28, '31.05.1997', 'Hane Group', 'dell.com');
insert into team (team_id, foundation_date, name, website_url) values (29, '19.09.1998', 'Wiegand Inc', null);
insert into team (team_id, foundation_date, name, website_url) values (30, '06.07.1994', 'Rowe, Daugherty and Ritchie', null);
insert into team (team_id, foundation_date, name, website_url) values (31, '19.05.1999', 'Marquardt Inc', null);
insert into team (team_id, foundation_date, name, website_url) values (32, '30.06.1991', 'Dietrich and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (33, '29.02.1992', 'Gutkowski, Parisian and Sawayn', null);
insert into team (team_id, foundation_date, name, website_url) values (34, '13.04.2003', 'Armstrong-Trantow', null);
insert into team (team_id, foundation_date, name, website_url) values (35, '12.02.1986', 'Ebert Group', null);
insert into team (team_id, foundation_date, name, website_url) values (36, '31.05.2004', 'Wehner and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (37, '10.03.1991', 'Goldner Inc', null);
insert into team (team_id, foundation_date, name, website_url) values (38, '06.10.1977', 'Walker LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (39, '13.04.2001', 'Bahringer, Nader and Kunze', 'artisteer.com');
insert into team (team_id, foundation_date, name, website_url) values (40, '26.04.2002', 'Rodriguez and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (41, '26.03.1980', 'Parker, Beahan and Mertz', 'blogger.com');
insert into team (team_id, foundation_date, name, website_url) values (42, '24.05.1991', 'Denesik, Altenwerth and Klein', null);
insert into team (team_id, foundation_date, name, website_url) values (43, '19.10.2004', 'Grady Inc', 'utexas.edu');
insert into team (team_id, foundation_date, name, website_url) values (44, '27.07.2001', 'Rippin, Cruickshank and Hoppe', null);
insert into team (team_id, foundation_date, name, website_url) values (45, '04.03.1990', 'Pfeffer Inc', null);
insert into team (team_id, foundation_date, name, website_url) values (46, '30.07.1975', 'Johnston and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (47, '02.02.1984', 'Pfeffer, Abbott and Waters', null);
insert into team (team_id, foundation_date, name, website_url) values (48, '11.08.1994', 'Roob-Watsica', null);
insert into team (team_id, foundation_date, name, website_url) values (49, '15.11.1993', 'Gottlieb, Skiles and Zemlak', null);
insert into team (team_id, foundation_date, name, website_url) values (50, '06.04.1991', 'O''Conner, Hagenes and Williamson', null);
