-- Team
insert into team (team_id, foundation_date, name, website_url) values (1, '9/4/2006', 'Macejkovic-Reilly', null);
insert into team (team_id, foundation_date, name, website_url) values (2, '10/23/2001', 'Marquardt-Jaskolski', null);
insert into team (team_id, foundation_date, name, website_url) values (3, '5/15/2009', 'Pfannerstill LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (4, '9/7/2010', 'Towne, Vandervort and Hammes', 'towne.com');
insert into team (team_id, foundation_date, name, website_url) values (5, '10/13/2010', 'Macejkovic and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (6, '9/19/2002', 'Paucek, Hammes and Walker', null);
insert into team (team_id, foundation_date, name, website_url) values (7, '3/5/2002', 'Zieme LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (8, '3/5/2002', 'Hilll-Legros', null);
insert into team (team_id, foundation_date, name, website_url) values (9, '5/1/2005', 'Ritchie, Considine and Marvin', 'ritchie-racing.com');
insert into team (team_id, foundation_date, name, website_url) values (10, '4/18/2007', 'Koelpin, Luettgen and Collins', 'koelpin.com');
insert into team (team_id, foundation_date, name, website_url) values (11, '1/11/2001', 'Dickens Group', null);
insert into team (team_id, foundation_date, name, website_url) values (12, '5/19/2008', 'Emmerich-Schuppe', null);
insert into team (team_id, foundation_date, name, website_url) values (13, '5/9/2008', 'Heaney Group', null);
insert into team (team_id, foundation_date, name, website_url) values (14, '12/14/2007', 'Hills, Hackett and Turner', null);
insert into team (team_id, foundation_date, name, website_url) values (15, '9/26/2002', 'Bradtke, McKenzie and Wilkinson', null);
insert into team (team_id, foundation_date, name, website_url) values (16, '1/30/2005', 'Emard Group', null);
insert into team (team_id, foundation_date, name, website_url) values (17, '7/20/2009', 'Bernier-Jast', 'bernier-jast.com');
insert into team (team_id, foundation_date, name, website_url) values (18, '1/19/2005', 'Rohan-Metz', null);
insert into team (team_id, foundation_date, name, website_url) values (19, '11/14/2010', 'Jacobson LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (20, '10/1/2010', 'Sipes and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (21, '7/8/2001', 'Dibbert, Marks and Becker', 'dibbert-racing.it');
insert into team (team_id, foundation_date, name, website_url) values (22, '9/20/2009', 'MacGyver, Monahan and Rempel', null);
insert into team (team_id, foundation_date, name, website_url) values (23, '10/28/2001', 'Abbott and Sons', null);
insert into team (team_id, foundation_date, name, website_url) values (24, '6/30/2009', 'Renner, Durgan and Hamill', null);
insert into team (team_id, foundation_date, name, website_url) values (25, '8/4/2001', 'Weber Group', null);
insert into team (team_id, foundation_date, name, website_url) values (26, '5/19/2006', 'Marquardt and Sons', 'marquardt.fr');
insert into team (team_id, foundation_date, name, website_url) values (27, '4/17/2008', 'Jones-Grady', null);
insert into team (team_id, foundation_date, name, website_url) values (28, '3/19/2003', 'Denesik, Collins and Feeney', null);
insert into team (team_id, foundation_date, name, website_url) values (29, '10/19/2010', 'Carter, Marquardt and Eichmann', null);
insert into team (team_id, foundation_date, name, website_url) values (30, '5/15/2003', 'Nienow LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (31, '8/9/2006', 'Hodkiewicz Group', null);
insert into team (team_id, foundation_date, name, website_url) values (32, '11/28/2006', 'Wuckert-Schamberger', null);
insert into team (team_id, foundation_date, name, website_url) values (33, '1/29/2009', 'Treutel, Murphy and Smith', null);
insert into team (team_id, foundation_date, name, website_url) values (34, '11/28/2008', 'Feil Inc', null);
insert into team (team_id, foundation_date, name, website_url) values (35, '1/30/2003', 'Kautzer LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (36, '2/16/2010', 'Torphy, Kuvalis and Tremblay', null);
insert into team (team_id, foundation_date, name, website_url) values (37, '3/13/2001', 'Olson, Hamill and Lakin', null);
insert into team (team_id, foundation_date, name, website_url) values (38, '6/21/2004', 'Botsford LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (39, '7/13/2008', 'Gorczany Inc', 'vk.com/cras/non/velit.js');
insert into team (team_id, foundation_date, name, website_url) values (40, '6/29/2009', 'Murazik-Ebert', 'symantec.com/eu/mi.js');
insert into team (team_id, foundation_date, name, website_url) values (41, '11/22/2005', 'Gerlach Group', 'gerlach-racing-group.de');
insert into team (team_id, foundation_date, name, website_url) values (42, '12/19/2003', 'Bosco LLC', null);
insert into team (team_id, foundation_date, name, website_url) values (43, '12/8/2009', 'Heller, Herman and Lockman', null);
insert into team (team_id, foundation_date, name, website_url) values (44, '1/14/2002', 'Rodriguez, Dibbert and Beahan', null);
insert into team (team_id, foundation_date, name, website_url) values (45, '2/20/2001', 'VonRueden Inc', null);
insert into team (team_id, foundation_date, name, website_url) values (46, '3/11/2006', 'Langworth, Wilderman and Mayert', null);
insert into team (team_id, foundation_date, name, website_url) values (47, '2/10/2004', 'Ferry Group', null);
insert into team (team_id, foundation_date, name, website_url) values (48, '1/10/2001', 'Mertz, Larkin and Schmeler', 'mertz.de');
insert into team (team_id, foundation_date, name, website_url) values (49, '10/10/2005', 'Braun, Dickinson and Beier', 'racing.braun.de');
insert into team (team_id, foundation_date, name, website_url) values (50, '5/29/2009', 'Runolfsdottir, Douglas and Kuhlman', 'okayracing.com');

-- Mechanic
insert into mechanic (mechanic_id, first_name, last_name) values (1, 'Tucker', 'Minnock');
insert into mechanic (mechanic_id, first_name, last_name) values (2, 'Jarrad', 'Kmieciak');
insert into mechanic (mechanic_id, first_name, last_name) values (3, 'Siward', 'Reddish');
insert into mechanic (mechanic_id, first_name, last_name) values (4, 'Tanny', 'McGonnell');
insert into mechanic (mechanic_id, first_name, last_name) values (5, 'Barnie', 'Wybern');
insert into mechanic (mechanic_id, first_name, last_name) values (6, 'Edvard', 'Tremmel');
insert into mechanic (mechanic_id, first_name, last_name) values (7, 'Dionysus', 'Abthorpe');
insert into mechanic (mechanic_id, first_name, last_name) values (8, 'Berkly', 'Blaksland');
insert into mechanic (mechanic_id, first_name, last_name) values (9, 'Pincas', 'Upchurch');
insert into mechanic (mechanic_id, first_name, last_name) values (10, 'Oswell', 'Whilde');
insert into mechanic (mechanic_id, first_name, last_name) values (11, 'Brigham', 'Bosomworth');
insert into mechanic (mechanic_id, first_name, last_name) values (12, 'Biron', 'Middell');
insert into mechanic (mechanic_id, first_name, last_name) values (13, 'Amos', 'Betser');
insert into mechanic (mechanic_id, first_name, last_name) values (14, 'Vern', 'Titcumb');
insert into mechanic (mechanic_id, first_name, last_name) values (15, 'Sigismund', 'Lochhead');
insert into mechanic (mechanic_id, first_name, last_name) values (16, 'Josiah', 'Palomba');
insert into mechanic (mechanic_id, first_name, last_name) values (17, 'Tynan', 'Teodorski');
insert into mechanic (mechanic_id, first_name, last_name) values (18, 'Reginauld', 'McCurry');
insert into mechanic (mechanic_id, first_name, last_name) values (19, 'Hort', 'Ferdinand');
insert into mechanic (mechanic_id, first_name, last_name) values (20, 'Jase', 'Iacabucci');
insert into mechanic (mechanic_id, first_name, last_name) values (21, 'Salomo', 'Neeson');
insert into mechanic (mechanic_id, first_name, last_name) values (22, 'Bay', 'Eilers');
insert into mechanic (mechanic_id, first_name, last_name) values (23, 'Waiter', 'Bygrove');
insert into mechanic (mechanic_id, first_name, last_name) values (24, 'Gare', 'Broadnicke');
insert into mechanic (mechanic_id, first_name, last_name) values (25, 'Cleon', 'New');
insert into mechanic (mechanic_id, first_name, last_name) values (26, 'Rossie', 'Chevin');
insert into mechanic (mechanic_id, first_name, last_name) values (27, 'Benedikt', 'Caplan');
insert into mechanic (mechanic_id, first_name, last_name) values (28, 'Jamison', 'Hobbert');
insert into mechanic (mechanic_id, first_name, last_name) values (29, 'Federico', 'O''Feeny');
insert into mechanic (mechanic_id, first_name, last_name) values (30, 'Foss', 'Benet');
insert into mechanic (mechanic_id, first_name, last_name) values (31, 'Benjamen', 'Yedall');
insert into mechanic (mechanic_id, first_name, last_name) values (32, 'Lev', 'Scamp');
insert into mechanic (mechanic_id, first_name, last_name) values (33, 'Tod', 'Kittow');
insert into mechanic (mechanic_id, first_name, last_name) values (34, 'Howey', 'Macveigh');
insert into mechanic (mechanic_id, first_name, last_name) values (35, 'Griswold', 'Senyard');
insert into mechanic (mechanic_id, first_name, last_name) values (36, 'Toddy', 'Purton');
insert into mechanic (mechanic_id, first_name, last_name) values (37, 'Thedrick', 'Cord');
insert into mechanic (mechanic_id, first_name, last_name) values (38, 'Geno', 'Crawley');
insert into mechanic (mechanic_id, first_name, last_name) values (39, 'Talbert', 'Smitheram');
insert into mechanic (mechanic_id, first_name, last_name) values (40, 'Reinwald', 'Sneaker');
insert into mechanic (mechanic_id, first_name, last_name) values (41, 'Mart', 'McQuode');
insert into mechanic (mechanic_id, first_name, last_name) values (42, 'Kenyon', 'Grishagin');
insert into mechanic (mechanic_id, first_name, last_name) values (43, 'Sergio', 'Featherstonhaugh');
insert into mechanic (mechanic_id, first_name, last_name) values (44, 'Mano', 'Leversuch');
insert into mechanic (mechanic_id, first_name, last_name) values (45, 'Dario', 'Mercik');
insert into mechanic (mechanic_id, first_name, last_name) values (46, 'Ingelbert', 'Sargint');
insert into mechanic (mechanic_id, first_name, last_name) values (47, 'Jedd', 'Kimbrey');
insert into mechanic (mechanic_id, first_name, last_name) values (48, 'Hugibert', 'Farguhar');
insert into mechanic (mechanic_id, first_name, last_name) values (49, 'Emanuel', 'Selburn');
insert into mechanic (mechanic_id, first_name, last_name) values (50, 'Bradan', 'Norree');
insert into mechanic (mechanic_id, first_name, last_name) values (51, 'Cello', 'Giannini');
insert into mechanic (mechanic_id, first_name, last_name) values (52, 'Timofei', 'Brosh');
insert into mechanic (mechanic_id, first_name, last_name) values (53, 'Sheridan', 'Bullent');
insert into mechanic (mechanic_id, first_name, last_name) values (54, 'Delmer', 'Fetherston');
insert into mechanic (mechanic_id, first_name, last_name) values (55, 'Kliment', 'McCroft');
insert into mechanic (mechanic_id, first_name, last_name) values (56, 'Arvin', 'Perris');
insert into mechanic (mechanic_id, first_name, last_name) values (57, 'Angelo', 'Pymer');
insert into mechanic (mechanic_id, first_name, last_name) values (58, 'Hewie', 'Bowmaker');
insert into mechanic (mechanic_id, first_name, last_name) values (59, 'Skipp', 'Hens');
insert into mechanic (mechanic_id, first_name, last_name) values (60, 'Weylin', 'Edmonds');
insert into mechanic (mechanic_id, first_name, last_name) values (61, 'Cristian', 'Spinetti');
insert into mechanic (mechanic_id, first_name, last_name) values (62, 'Vernor', 'Shewen');
insert into mechanic (mechanic_id, first_name, last_name) values (63, 'Shermie', 'Toffel');
insert into mechanic (mechanic_id, first_name, last_name) values (64, 'Filmer', 'Harmon');
insert into mechanic (mechanic_id, first_name, last_name) values (65, 'Gaile', 'Higford');
insert into mechanic (mechanic_id, first_name, last_name) values (66, 'Daryl', 'Plampin');
insert into mechanic (mechanic_id, first_name, last_name) values (67, 'Thorsten', 'Racher');
insert into mechanic (mechanic_id, first_name, last_name) values (68, 'Timothy', 'Greensitt');
insert into mechanic (mechanic_id, first_name, last_name) values (69, 'Erek', 'Eitter');
insert into mechanic (mechanic_id, first_name, last_name) values (70, 'Toby', 'Yuryshev');
insert into mechanic (mechanic_id, first_name, last_name) values (71, 'Jere', 'Possek');
insert into mechanic (mechanic_id, first_name, last_name) values (72, 'Cyril', 'Sewall');
insert into mechanic (mechanic_id, first_name, last_name) values (73, 'Mord', 'Bearblock');
insert into mechanic (mechanic_id, first_name, last_name) values (74, 'Jeth', 'Dennes');
insert into mechanic (mechanic_id, first_name, last_name) values (75, 'Arley', 'Blemings');
insert into mechanic (mechanic_id, first_name, last_name) values (76, 'Man', 'Widdecombe');
insert into mechanic (mechanic_id, first_name, last_name) values (77, 'Elwood', 'Reaper');
insert into mechanic (mechanic_id, first_name, last_name) values (78, 'Alfonso', 'Mottershead');
insert into mechanic (mechanic_id, first_name, last_name) values (79, 'Ahmed', 'Mangeney');
insert into mechanic (mechanic_id, first_name, last_name) values (80, 'Rocky', 'Gruby');
insert into mechanic (mechanic_id, first_name, last_name) values (81, 'Jephthah', 'Deares');
insert into mechanic (mechanic_id, first_name, last_name) values (82, 'Chadwick', 'Matovic');
insert into mechanic (mechanic_id, first_name, last_name) values (83, 'Haily', 'Robart');
insert into mechanic (mechanic_id, first_name, last_name) values (84, 'Randal', 'Hultberg');
insert into mechanic (mechanic_id, first_name, last_name) values (85, 'Gabie', 'Keling');
insert into mechanic (mechanic_id, first_name, last_name) values (86, 'Deane', 'MacDaid');
insert into mechanic (mechanic_id, first_name, last_name) values (87, 'Adolpho', 'Santorini');
insert into mechanic (mechanic_id, first_name, last_name) values (88, 'Vincents', 'Ashfold');
insert into mechanic (mechanic_id, first_name, last_name) values (89, 'Enoch', 'Bromby');
insert into mechanic (mechanic_id, first_name, last_name) values (90, 'Woodman', 'Dennington');
insert into mechanic (mechanic_id, first_name, last_name) values (91, 'Pail', 'Stanley');
insert into mechanic (mechanic_id, first_name, last_name) values (92, 'Fred', 'Wilkinson');
insert into mechanic (mechanic_id, first_name, last_name) values (93, 'Launce', 'Carslaw');
insert into mechanic (mechanic_id, first_name, last_name) values (94, 'Ellery', 'O''Loughane');
insert into mechanic (mechanic_id, first_name, last_name) values (95, 'Findlay', 'McAllister');
insert into mechanic (mechanic_id, first_name, last_name) values (96, 'Desmond', 'Scarlet');
insert into mechanic (mechanic_id, first_name, last_name) values (97, 'Cleveland', 'Wheeliker');
insert into mechanic (mechanic_id, first_name, last_name) values (98, 'Dino', 'Pedrocchi');
insert into mechanic (mechanic_id, first_name, last_name) values (99, 'Sandor', 'Simond');
insert into mechanic (mechanic_id, first_name, last_name) values (100, 'Trev', 'O''Rodane');
insert into mechanic (mechanic_id, first_name, last_name) values (101, 'Rodney', 'Poland');
insert into mechanic (mechanic_id, first_name, last_name) values (102, 'Brock', 'Ioannidis');
insert into mechanic (mechanic_id, first_name, last_name) values (103, 'Armand', 'Fussell');
insert into mechanic (mechanic_id, first_name, last_name) values (104, 'Orran', 'Ridgway');
insert into mechanic (mechanic_id, first_name, last_name) values (105, 'Bancroft', 'Iwanowicz');
insert into mechanic (mechanic_id, first_name, last_name) values (106, 'Fleming', 'Luckman');
insert into mechanic (mechanic_id, first_name, last_name) values (107, 'Alexandros', 'Dalrymple');
insert into mechanic (mechanic_id, first_name, last_name) values (108, 'Francisco', 'Whittet');
insert into mechanic (mechanic_id, first_name, last_name) values (109, 'Paquito', 'MacRedmond');
insert into mechanic (mechanic_id, first_name, last_name) values (110, 'Alfonso', 'Cosins');
insert into mechanic (mechanic_id, first_name, last_name) values (111, 'Kile', 'Kelshaw');
insert into mechanic (mechanic_id, first_name, last_name) values (112, 'Johnnie', 'Premble');
insert into mechanic (mechanic_id, first_name, last_name) values (113, 'Chrissy', 'Minico');
insert into mechanic (mechanic_id, first_name, last_name) values (114, 'Elisha', 'de Quincey');
insert into mechanic (mechanic_id, first_name, last_name) values (115, 'Hermon', 'Yansons');
insert into mechanic (mechanic_id, first_name, last_name) values (116, 'Neill', 'Ropkins');
insert into mechanic (mechanic_id, first_name, last_name) values (117, 'Carney', 'Midford');
insert into mechanic (mechanic_id, first_name, last_name) values (118, 'Dell', 'Cogdell');
insert into mechanic (mechanic_id, first_name, last_name) values (119, 'Rab', 'Limmer');
insert into mechanic (mechanic_id, first_name, last_name) values (120, 'Raddy', 'Vautre');
insert into mechanic (mechanic_id, first_name, last_name) values (121, 'Giraud', 'Bernardt');
insert into mechanic (mechanic_id, first_name, last_name) values (122, 'Lazare', 'Dmytryk');
insert into mechanic (mechanic_id, first_name, last_name) values (123, 'Orville', 'McGuinness');
insert into mechanic (mechanic_id, first_name, last_name) values (124, 'Sim', 'Louthe');
insert into mechanic (mechanic_id, first_name, last_name) values (125, 'Hussein', 'Douce');
insert into mechanic (mechanic_id, first_name, last_name) values (126, 'Hailey', 'Joanic');
insert into mechanic (mechanic_id, first_name, last_name) values (127, 'Humphrey', 'Stenhouse');
insert into mechanic (mechanic_id, first_name, last_name) values (128, 'Kyle', 'Spinke');
insert into mechanic (mechanic_id, first_name, last_name) values (129, 'Hercule', 'Osinin');
insert into mechanic (mechanic_id, first_name, last_name) values (130, 'Gunther', 'Chappelow');
insert into mechanic (mechanic_id, first_name, last_name) values (131, 'Merv', 'Fergyson');
insert into mechanic (mechanic_id, first_name, last_name) values (132, 'Georg', 'Arnaldy');
insert into mechanic (mechanic_id, first_name, last_name) values (133, 'Dermot', 'Mateu');
insert into mechanic (mechanic_id, first_name, last_name) values (134, 'Remington', 'Zuan');
insert into mechanic (mechanic_id, first_name, last_name) values (135, 'Alfonso', 'Espinola');
insert into mechanic (mechanic_id, first_name, last_name) values (136, 'Rourke', 'Nerney');
insert into mechanic (mechanic_id, first_name, last_name) values (137, 'Allard', 'Pandya');
insert into mechanic (mechanic_id, first_name, last_name) values (138, 'Barron', 'Corner');
insert into mechanic (mechanic_id, first_name, last_name) values (139, 'Thain', 'Wipfler');
insert into mechanic (mechanic_id, first_name, last_name) values (140, 'James', 'Axon');
insert into mechanic (mechanic_id, first_name, last_name) values (141, 'Leif', 'Atcock');
insert into mechanic (mechanic_id, first_name, last_name) values (142, 'Zacharia', 'Rivitt');
insert into mechanic (mechanic_id, first_name, last_name) values (143, 'Aldin', 'Steeden');
insert into mechanic (mechanic_id, first_name, last_name) values (144, 'Stefan', 'Coope');
insert into mechanic (mechanic_id, first_name, last_name) values (145, 'Doyle', 'Garrood');
insert into mechanic (mechanic_id, first_name, last_name) values (146, 'Mannie', 'Ancketill');
insert into mechanic (mechanic_id, first_name, last_name) values (147, 'Barclay', 'Deerr');
insert into mechanic (mechanic_id, first_name, last_name) values (148, 'Erastus', 'Marin');
insert into mechanic (mechanic_id, first_name, last_name) values (149, 'Cchaddie', 'Walsham');
insert into mechanic (mechanic_id, first_name, last_name) values (150, 'Jason', 'Kepe');
insert into mechanic (mechanic_id, first_name, last_name) values (151, 'Renaud', 'Lardeur');
insert into mechanic (mechanic_id, first_name, last_name) values (152, 'Christophorus', 'Mussett');
insert into mechanic (mechanic_id, first_name, last_name) values (153, 'Cary', 'Monckton');
insert into mechanic (mechanic_id, first_name, last_name) values (154, 'Luis', 'Sloan');
insert into mechanic (mechanic_id, first_name, last_name) values (155, 'Shem', 'Atmore');
insert into mechanic (mechanic_id, first_name, last_name) values (156, 'Gardy', 'Gasnell');
insert into mechanic (mechanic_id, first_name, last_name) values (157, 'Basilio', 'Ganing');
insert into mechanic (mechanic_id, first_name, last_name) values (158, 'Doyle', 'Erley');
insert into mechanic (mechanic_id, first_name, last_name) values (159, 'Dilly', 'Bourke');
insert into mechanic (mechanic_id, first_name, last_name) values (160, 'Ferrel', 'Casina');
insert into mechanic (mechanic_id, first_name, last_name) values (161, 'Reinald', 'Belchem');
insert into mechanic (mechanic_id, first_name, last_name) values (162, 'Simmonds', 'Roswarne');
insert into mechanic (mechanic_id, first_name, last_name) values (163, 'Bronny', 'Slarke');
insert into mechanic (mechanic_id, first_name, last_name) values (164, 'Marve', 'Rivenzon');
insert into mechanic (mechanic_id, first_name, last_name) values (165, 'Emmett', 'Weakley');
insert into mechanic (mechanic_id, first_name, last_name) values (166, 'Camey', 'Brownsmith');
insert into mechanic (mechanic_id, first_name, last_name) values (167, 'Terence', 'Ludron');
insert into mechanic (mechanic_id, first_name, last_name) values (168, 'Natal', 'Pakeman');
insert into mechanic (mechanic_id, first_name, last_name) values (169, 'Ricki', 'Swains');
insert into mechanic (mechanic_id, first_name, last_name) values (170, 'Basile', 'Dosdell');
insert into mechanic (mechanic_id, first_name, last_name) values (171, 'Obediah', 'Jost');
insert into mechanic (mechanic_id, first_name, last_name) values (172, 'Konstantin', 'Collings');
insert into mechanic (mechanic_id, first_name, last_name) values (173, 'Benedetto', 'Fauguel');
insert into mechanic (mechanic_id, first_name, last_name) values (174, 'Marty', 'Croston');
insert into mechanic (mechanic_id, first_name, last_name) values (175, 'Obie', 'Storrah');
insert into mechanic (mechanic_id, first_name, last_name) values (176, 'Lamond', 'Thorndycraft');
insert into mechanic (mechanic_id, first_name, last_name) values (177, 'Sholom', 'Ryrie');
insert into mechanic (mechanic_id, first_name, last_name) values (178, 'Basilius', 'Claybourn');
insert into mechanic (mechanic_id, first_name, last_name) values (179, 'Win', 'L''Episcopio');
insert into mechanic (mechanic_id, first_name, last_name) values (180, 'Sutherland', 'Coan');
insert into mechanic (mechanic_id, first_name, last_name) values (181, 'Ludvig', 'Olivey');
insert into mechanic (mechanic_id, first_name, last_name) values (182, 'Sidnee', 'Vousden');
insert into mechanic (mechanic_id, first_name, last_name) values (183, 'Tucky', 'Petrou');
insert into mechanic (mechanic_id, first_name, last_name) values (184, 'Em', 'Walaron');
insert into mechanic (mechanic_id, first_name, last_name) values (185, 'Spencer', 'Hammerson');
insert into mechanic (mechanic_id, first_name, last_name) values (186, 'Alexander', 'Pimblett');
insert into mechanic (mechanic_id, first_name, last_name) values (187, 'Clarence', 'Cardillo');
insert into mechanic (mechanic_id, first_name, last_name) values (188, 'Quintus', 'Crinson');
insert into mechanic (mechanic_id, first_name, last_name) values (189, 'Olvan', 'MacLardie');
insert into mechanic (mechanic_id, first_name, last_name) values (190, 'Christoph', 'Browse');
insert into mechanic (mechanic_id, first_name, last_name) values (191, 'Jayson', 'Fanti');
insert into mechanic (mechanic_id, first_name, last_name) values (192, 'Hubert', 'Dearnaley');
insert into mechanic (mechanic_id, first_name, last_name) values (193, 'Beau', 'Hallbord');
insert into mechanic (mechanic_id, first_name, last_name) values (194, 'Roland', 'Landy');
insert into mechanic (mechanic_id, first_name, last_name) values (195, 'Myrwyn', 'Hassekl');
insert into mechanic (mechanic_id, first_name, last_name) values (196, 'Isaiah', 'Cawkwell');
insert into mechanic (mechanic_id, first_name, last_name) values (197, 'Gery', 'Alpe');
insert into mechanic (mechanic_id, first_name, last_name) values (198, 'Cornell', 'Jesteco');
insert into mechanic (mechanic_id, first_name, last_name) values (199, 'Mathias', 'Gobolos');
insert into mechanic (mechanic_id, first_name, last_name) values (200, 'Windham', 'Schoenrock');

-- Male Driver
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (1, 'Sherman', 'Naisbet', '7/17/1982', 'male', 'RS', 'naisbet.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (2, 'Ermin', 'Simo', '3/8/1990', 'male', 'BR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (3, 'Max', 'Ferreiro', '5/30/1987', 'male', 'RE', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (4, 'Horton', 'Gethin', '7/6/1998', 'male', 'RU', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (5, 'Rosco', 'Wackett', '11/16/1981', 'male', 'TN', 'wackett.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (6, 'Frasier', 'Redwing', '9/13/1993', 'male', 'ES', 'redwing-racing.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (7, 'Tracie', 'Devericks', '6/2/1995', 'male', 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (8, 'Joshia', 'Songest', '12/31/1991', 'male', 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (9, 'Kahaleel', 'Kike', '11/22/1979', 'male', 'NR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (10, 'Bartolomeo', 'Jinkin', '1/28/1983', 'male', 'CZ', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (11, 'Hagen', 'Pregel', '1/7/1990', 'male', 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (12, 'Kipper', 'Burchatt', '9/14/1989', 'male', 'FR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (13, 'Pattie', 'De Hooge', '7/27/1993', 'male', 'FR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (14, 'Pierce', 'McMylor', '7/27/1994', 'male', 'CN', 'mcmylor.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (15, 'Dominique', 'MacCostye', '10/16/1991', 'male', 'PT', 'maccostye.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (16, 'Orran', 'Buckam', '12/18/1991', 'male', 'FR', 'buckam.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (17, 'Wash', 'Sarl', '3/4/1997', 'male', 'PL', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (18, 'Sydney', 'Nuss', '8/30/1989', 'male', 'CN', 'nuss.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (19, 'Quillan', 'MacTrustam', '4/5/1988', 'male', 'BR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (20, 'Wallis', 'Brabbs', '9/28/1981', 'male', 'TH', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (21, 'Griz', 'Nolleth', '5/17/1982', 'male', 'PT', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (22, 'Cobbie', 'Mulhill', '5/28/1986', 'male', 'CN', 'mulhill.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (23, 'Burke', 'Georgievski', '1/16/1994', 'male', 'TW', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (24, 'Moise', 'Bows', '11/20/1994', 'male', 'AR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (25, 'Omero', 'Keyson', '10/6/1980', 'male', 'RU', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (26, 'Yul', 'Pryell', '1/10/1987', 'male', 'RU', 'pryell-racing.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (27, 'Wilek', 'Speak', '4/20/1997', 'male', 'RU', 'speak.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (28, 'Sigmund', 'Willoughby', '7/8/1998', 'male', 'ID', 'sigmund-racing.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (29, 'Reginald', 'Crisford', '6/22/1997', 'male', 'ID', 'crisford.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (30, 'Obediah', 'Anscott', '4/7/1996', 'male', 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (31, 'Fee', 'Houlaghan', '6/2/1994', 'male', 'PH', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (32, 'Russ', 'Uppett', '10/8/1992', 'male', 'NG', 'uppett-racing.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (33, 'Garth', 'Mogey', '5/20/1980', 'male', 'LK', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (34, 'Alon', 'Breton', '12/5/1987', 'male', 'YE', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (35, 'Krisha', 'Southers', '5/15/1994', 'male', 'PH', 'southers.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (36, 'Gabriello', 'Vane', '3/28/1995', 'male', 'PL', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (37, 'Dene', 'Phorsby', '11/22/1991', 'male', 'EC', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (38, 'Ruby', 'Cowen', '12/5/1988', 'male', 'RU', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (39, 'Ban', 'Henniger', '6/8/1983', 'male', 'MX', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (40, 'Monty', 'Tupie', '9/26/1981', 'male', 'SE', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (41, 'Mahmud', 'Bruinemann', '11/2/1995', 'male', 'PH'bruinemann-racing.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (42, 'Saunderson', 'Crummey', '5/30/1978', 'male', 'ID', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (43, 'Derby', 'Hrihorovich', '12/11/1990', 'male', 'BR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (44, 'Swen', 'Peter', '2/23/1985', 'male', 'ZW', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (45, 'Syman', 'Linge', '9/1/1985', 'male', 'RU', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (46, 'Olav', 'Woolmore', '3/24/1990', 'male', 'CZ', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (47, 'Jeremias', 'O''Halligan', '12/28/1982', 'male', 'PH', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (48, 'Linus', 'Pawnsford', '7/1/1987', 'male', 'AF', 'pawnsford-racing.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (49, 'Lazaro', 'Tease', '6/7/1980', 'male', 'UA', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (50, 'Tucky', 'Galero', '8/8/1998', 'male', 'LV', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (51, 'Langsdon', 'Slader', '8/23/1979', 'male', 'FR', 'slader.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (52, 'Derry', 'Kenen', '3/26/1997', 'male', 'RU', 'kenen.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (53, 'Cozmo', 'Riguard', '12/21/1982', 'male', 'ID', 'riguard.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (54, 'Lonnard', 'Dunnett', '11/14/1980', 'male', 'ID', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (55, 'Kelsey', 'Witcombe', '6/27/1985', 'male', 'CN', 'witcombe.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (56, 'Andras', 'Penylton', '3/15/1995', 'male', 'FR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (57, 'Llywellyn', 'Kitchener', '11/4/1983', 'male', 'AL', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (58, 'Rogers', 'Torn', '12/2/1979', 'male', 'BR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (59, 'Giles', 'Wragg', '11/20/1994', 'male', 'BR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (60, 'Emery', 'Doxsey', '11/23/1978', 'male', 'ID', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (61, 'Randell', 'Paeckmeyer', '7/25/1982', 'male', 'AM', 'paeckmayer.racing.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (62, 'Lazar', 'Leadley', '2/19/1985', 'male', 'TZ', 'leadley.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (63, 'Orran', 'MacAlees', '12/18/1982', 'male', 'PH', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (64, 'Hashim', 'Copeland', '4/8/1985', 'male', 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (65, 'Trstram', 'Head', '3/13/1996', 'male', 'RU', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (66, 'Darcy', 'Orts', '1/6/1984', 'male', 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (67, 'Morrie', 'Elderidge', '1/6/1985', 'male', 'TN', 'elderidge.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (68, 'Eustace', 'Mion', '3/13/1978', 'male', 'GA', 'mion.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (69, 'Raimund', 'Isacke', '1/28/1978', 'male', 'SO', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (70, 'Barn', 'Hurdiss', '6/6/1984', 'male', 'SE', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (71, 'Kinnie', 'Harbron', '1/10/1984', 'male', 'PH', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (72, 'Colver', 'Arblaster', '1/15/1988', 'male', 'MY', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (73, 'Mathias', 'Wittrington', '2/15/1984', 'male', 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (74, 'Dael', 'Pember', '8/31/1980', 'male', 'NL', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (75, 'Even', 'Spracklin', '7/21/1983', 'male', 'CO', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (76, 'Frazer', 'Crowhurst', '12/22/1977', 'male', 'GR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (77, 'Maison', 'Philippeaux', '12/8/1978', 'male', 'UA', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (78, 'Osgood', 'Hobson', '2/13/1982', 'male', 'TH', 'hobson.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (79, 'Lev', 'Paridge', '8/23/1997', 'male', 'NP', 'paridge.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (80, 'Kimble', 'Eames', '3/17/1986', 'male', 'BR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (81, 'Kev', 'Delacour', '1/23/1984', 'male', 'US', 'delacour.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (82, 'Barrie', 'Furlow', '3/21/1978', 'male', 'BR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (83, 'Homer', 'Burkinshaw', '5/25/1997', 'male', 'NG', 'burkinshaw-racing.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (84, 'Natale', 'Fermer', '3/2/1989', 'male', 'RU', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (85, 'Drew', 'Domican', '2/14/1988', 'male', 'ID', 'domican-racing.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (86, 'Donnie', 'Grassin', '1/15/1984', 'male', 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (87, 'Milton', 'Brydon', '1/22/1981', 'male', 'ID', 'brydon.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (88, 'Way', 'Hatfull', '6/27/1998', 'male', 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (89, 'Alfy', 'Syddall', '5/5/1992', 'male', 'RU', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (90, 'Willey', 'Skillanders', '8/8/1987', 'male', 'CN', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (91, 'Webster', 'Veasey', '7/9/1991', 'male', 'CN', 'veasey.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (92, 'Ulises', 'Zuker', '8/12/1985', 'male', 'CN', 'zuker.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (93, 'Everard', 'Jecock', '1/6/1996', 'male', 'ID', 'jecock-racing.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (94, 'Yance', 'Tapsell', '9/27/1985', 'male', 'UA', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (95, 'Pebrook', 'Dealy', '1/12/1992', 'male', 'CN', 'dealy.racing');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (96, 'Kristos', 'Campsall', '12/12/1991', 'male', 'FI', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (97, 'Pace', 'Esby', '2/6/1992', 'male', 'GR', 'esby-fast-pace.com');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (98, 'Jeffie', 'Wellbelove', '5/2/1996', 'male', 'PE', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (99, 'Reuven', 'Labet', '3/6/1998', 'male', 'BR', 'reuven-racing.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (100, 'Percy', 'Domsalla', '4/21/1981', 'male', 'GR', null);

-- Female Driver
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (1, 'Roseann', 'Stienham', '10/15/1986', 'female', 'ID', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (2, 'Benedikta', 'Hadgkiss', '9/18/1995', 'female', 'BR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (3, 'Kerrie', 'Slevin', '10/30/1985', 'female', 'PH', 'slevin.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (4, 'Adelle', 'Coughan', '1/17/1979', 'female', 'CA', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (5, 'Josefina', 'Kearle', '7/20/1994', 'female', 'HR', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (6, 'Joni', 'Feeley', '5/18/1991', 'female', 'CM', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (7, 'Bettina', 'Skillern', '1/17/1980', 'female', 'CA', 'skillern.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (8, 'Louisette', 'Corbert', '11/12/1979', 'female', 'RU', 'corbert.eu');
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (9, 'Odelia', 'Baxendale', '2/26/1995', 'female', 'EG', null);
insert into driver (driver_id, first_name, last_name, birth_date, gender, nationality, website_url) values (10, 'Trula', 'Craxford', '11/3/1990', 'female', 'TJ', 'craxford-racing.com');

-- Circuit
insert into circuit (circuit_id, name, country, corners, length, car_capacity, viewers_capacity) values (1, 'Zolder', 'BE', 10, 4011, 26, 8010);
insert into circuit (circuit_id, name, country, corners, length, car_capacity, viewers_capacity) values (2, 'Monza', 'IT', 9, 5793, 40, 3440);
insert into circuit (circuit_id, name, country, corners, length, car_capacity, viewers_capacity) values (3, 'Brands Hatch', 'GB', 7, 4207, 36, 15474);
insert into circuit (circuit_id, name, country, corners, length, car_capacity, viewers_capacity) values (4, 'Silverstone', 'GB', 20, 5891, 38, 14533);
insert into circuit (circuit_id, name, country, corners, length, car_capacity, viewers_capacity) values (5, 'Paul Ricard', 'FR', 10, 3813, 35, 13401);
insert into circuit (circuit_id, name, country, corners, length, car_capacity, viewers_capacity) values (6, 'Misano', 'IT', 16, 4226, 31, 3671);
insert into circuit (circuit_id, name, country, corners, length, car_capacity, viewers_capacity) values (7, 'Spa', 'BE', 20, 7004, 32, 16098);
insert into circuit (circuit_id, name, country, corners, length, car_capacity, viewers_capacity) values (8, 'Hungaroring', 'HU', 16, 4381, 31, 18365);
insert into circuit (circuit_id, name, country, corners, length, car_capacity, viewers_capacity) values (9, 'Nurburgring', 'GE', 14, 5148, 39, 13587);
insert into circuit (circuit_id, name, country, corners, length, car_capacity, viewers_capacity) values (10, 'Barcelona', 'ES', 16, 4655, 35, 10329);

